### PR TITLE
Deleting deleted node, breadcrumbsNode and navigationNode

### PR DESCRIPTION
**Pull request by iFlameing**
Related to #184 this is an initial commit

### CODE REVIEW

**Comment by iFlameing** [comment]
> Have you already looked into updating parent’s navigation node after deletion?
> 
> There’s also catch: when deleting folder with children, the deletion event should be fired for each object separately. That works fine when just removing nodes, but updating parent’s navigation may fail, because parent has also been deleted. That should be taken account, probably with try {} catch (e) {}

I am facing the same problem right now that's why I am not updating the parent. because If we try to update parent of a nested child we are getting the internal server error because the parent is already deleted. Can You help me how should I tackle this problem?

**Comment by iFlameing** [comment]
@datakurre I am thinking that if we wrap the fetchUrl method into a try-catch block and Just return when we got an error. But I am not sure about this approach :)

**Comment by datakurre** [comment]
Is it really internal server error, because it should be “not found”.

Try catch blog should be ok for now. It might be that there really is no simpler option to check if a page exist.

**Comment by iFlameing** [comment]
@datakurre can you review this again I implemented the try and catch blog and tested the edge case :)

**Pull request merged**
