### PR TITLE
Migrate to Gatsby v2

### PR DESCRIPTION
**Pull request by ajayns**
The plugin didn't require many changes, but the tester project required many major changes.

* Layout has been to components
* Didn't have to remove gatsby-plugin-sass, got a workaround using node-sass
* Added Layout container for all templates

### CODE REVIEW

**Comment by ajayns** [comment]
I'm unsure why we require Gatsby in the plugin devDependencies but if it's required, we'll need to update that as well: https://github.com/collective/gatsby-source-plone/blob/21225839ab2ecaa3b4ead0cfcab5da6bc5405073/package.json#L32

**Comment by datakurre** [comment]
@ajayns I believe the test project is supposed to work also outside the main repo and that why it requires gatsby. Please, update :)

**Comment by ajayns** [comment]
That's quite weird, it's working fine locally but Travis seems to fail with an error I can't seem to make sense of.

**Comment by datakurre** [comment]
Strange. I did purge Travis caches just in case, but that did not have any effect.

Have you tried running tests with a clean clone?

**Comment by datakurre** [comment]
I seem to have the same issue locally.

**Comment by ajayns** [comment]
Yes, I did run it on a clean clone and still seems to be working ok. Let me see what I can do here.

**Comment by ajayns** [comment]
@datakurre Since it looks like something to do with Babel transpilation, I'll try adding a plugin for async generators and see if that has any effect on Travis?

**Comment by ajayns** [comment]
Looks like Gatsby v2 updated their transpilation setup as well. So I had to include this babel-runtime which handles polyfills for async/await.

**Comment by datakurre** [comment]
@ajayns Did you see my pull to your branch? :)

**Comment by datakurre** [comment]
Btw, it was nice to see that the build got faster.

**Comment by ajayns** [comment]
> Did you see my pull to your branch? :)

I didn't get what you mean? I didn't get any notification on a pull so I tried workarounds myself. 

> Btw, it was nice to see that the build got faster.

Yes glad that we have some improvements.

**Pull request merged**
