### PR TITLE
Changing custom Logging utility to reporter API

### LINKED ISSUE #182: Replace custom logging utility with use of gatsby reporter API
https://www.gatsbyjs.org/docs/node-api-helpers/#reporter

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #182

### CODE REVIEW

**Comment by iFlameing** [comment]
@datakurre can you merge this?please!

**Comment by iFlameing** [comment]
@datakurre I have read the docs regarding the reporter API https://www.gatsbyjs.org/docs/node-api-helpers/#reporter but Didn't find anything like reporter.log but in source code it is mention. I will ask Gatsby community for that :). After receiving the reply I will make modification as you suggested.

**Comment by iFlameing** [comment]
@datakurre I asked this question on twitter and kylemathews said me to open an issue for clarification or feature regarding that. You can see the reply at this link.https://twitter.com/iFlameing/status/1160172956942602240
I open an issue at gatsby regarding this https://github.com/gatsbyjs/gatsby/issues/16519

Can you merge this for now, So that I can refactor the whole codebase into a separate file? I will reopen this issue once the above issue is resolved in gatsby community. what do you think?

**Comment by datakurre** [comment]
Sure. Thanks!

**Pull request merged**
