### PR TITLE
Upgrade to Babel 7

### LINKED ISSUE #116: Upgrade to Babel 7
https://v2--gatsbyjs.netlify.com/docs/babel/#how-to-use-a-custom-babelrc-file

Probably should be done only when V2 is released (or when we found issues with Babel 6).

### PR DESCRIPTION
**Pull request by datakurre**
Fixes #116.

### CODE REVIEW

**Comment by ajayns** [comment]
@datakurre You may have accidentally (or maybe you're planning to do something) removed scripts from package.json, without it npm scripts won't be able to be run directly right?

**Comment by datakurre** [comment]
Yes. That’s one reason for WIP.

I was surprised that ”yarn install” called ”build” cmd from package.json. That broke things, but probably because I had updated babel cmd there.

Personally I prefer make over npm scripts, but I try to restore them.

**Comment by ajayns** [comment]
Yes we've automated the workflow with Make and could use them only, but isn't it still good to have the npm scripts still so that the developer has full control individually over what is to be done and for JavaScript devs, I think they'd be expecting this as well.

**Comment by datakurre** [comment]
I restored npm scripts, but forcing babel 7 is still wip.

**Comment by ajayns** [comment]
Just curious, but in the process of upgrading to Babel 7, why was it required to create a new arrangement of dependencies and devDependencies? What's the practise to be followed for this?

**Comment by datakurre** [comment]
@ajayns Not necessary, but I thought it to be a mistake to have babel as a direct dependency for the plugin. AFAIK installing plugin with npm should install compiled version without dependency on babel.

But it was necessary to fix gatsby-source-filesystem to next-version, because the 1.x pulled babel 6 with it.

**Pull request merged**
