### PR TITLE
Create Plone Site node for @search traversed data

### PR DESCRIPTION
**Pull request by ajayns**
Addresses #60 

I've come up with the workaround of adding the baseURL item to the array so that it's processed with the others.

### CODE REVIEW

**Comment by ajayns** [comment]
On it, also we I just realized this would create a node of type `PlonePloneSite` I think, will need to be fixed yes?

**Comment by datakurre** [comment]
Nice catch. Yes. Please. Change :) PlonePloneSite does not make sense.

**Comment by ajayns** [comment]
On it, also we I just realized this would create a node of type `PlonePloneSite` I think, will need to be fixed yes?

**Comment by datakurre** [comment]
”Right” way might be to do 1. now and 2. only when it is required, but let’s do 2. so it is done forever.

**Comment by ajayns** [comment]
@datakurre hey, I was exploring the restapi a bit with Postman and the PloneSite node wouldn't be containing much data at all... So I didn't exactly understand what

**Comment by ajayns** [comment]
Yes I've done 2. And sorry, I closed it by mistake!

**Comment by ajayns** [comment]
About dynamically creating an `index` page using `PloneSite`, I didn't quite get what data it can include. I'll have to query for children of `PloneSite` and use GraphQL fragment to display document data?

**Comment by datakurre** [comment]
It contains title, description and items.

Items are important. They make it possible to do graphql for PloneSite and replace pages/index from page created from that.

That reminds me something requiring one more rewrite for this. I believe that any content found at baseUrl should be added into gatsby as PloneSite. That would allow generic gatsby example starting rendering from PloneSite work properly regardless of baseUrl.

**Comment by datakurre** [comment]
If you didn’t understand yet the previous comment, please, look how the current test site works: every page except index and 404 are generated. And in my idea about PloneSite, also index could be generated. Obviously index would usually have at least a custom template, but for me generating also index sound like a good default.

**Comment by ajayns** [comment]
> That reminds me something requiring one more rewrite for this. I believe that any content found at baseUrl should be added into gatsby as PloneSite. That would allow generic gatsby example starting rendering from PloneSite work properly regardless of baseUrl.

So the best workaround for this I can think of is instead of pushing to the items array we'll process this node separately. 

> Obviously index would usually have at least a custom template, but for me generating also index sound like a good default.

So basically you mean to say, I'll create another template for `index` and create it as a page in `gatsby-node` by querying for `allPloneSite` as well?

**Comment by datakurre** [comment]
@ajayns Yes, processing it separately might actually be better. I'm sorry for not figuring out that in the first place.

About templates. It might even be enough to use templates/default.js also for PloneSite and then customize it using components, as it is done currently for the other page types.

**Comment by ajayns** [comment]
This is probably gonna a make a few tests fail. 
I was unable to get the content of the `gatsby-source-plugin` doc in the index, also I couldn't retrieve the `slugs` from the items property as all they have is `title` and `description` data.
What would you recommend for this @datakurre ?

**Comment by datakurre** [comment]
@ajayns ``index`` from doc has been filtered in ``gatsby-node.js`` of the test project with ``pages`` variable

* https://github.com/collective/gatsby-source-plone/commit/d747d3a10cfbb66f6a86f1132908e733ce8916f8#diff-95625949ad83ff72ab615b7238384ba0R29
* https://github.com/collective/gatsby-source-plone/commit/d747d3a10cfbb66f6a86f1132908e733ce8916f8#diff-95625949ad83ff72ab615b7238384ba0R70

**Comment by datakurre** [comment]
@ajayns slugs could be calculated from @id:

https://github.com/collective/gatsby-source-plone/commit/d747d3a10cfbb66f6a86f1132908e733ce8916f8#diff-95625949ad83ff72ab615b7238384ba0R20

**Comment by ajayns** [comment]
> index from doc has been filtered in gatsby-node.js of the test project with pages variable

I've understood this part, I've retained it to prevent 2 index pages happening. But what I meant was that, the only content that's displayed in the index right now is the list of items because I'm not getting the data of the document `gatsby-source-plugin`

> slugs could be calculated from id:

Hmm so I could use this in the `PloneSite` component to get slugs is what you're suggesting yes?

**Comment by datakurre** [comment]
@ajayns I've now understood that ``./page/index.js`` will be at ``/`` so ``./docs/index`` being at ``/index`` might not introduce index page conflicts after all.

Getting contents of ``index`` (``gatsby-source-plone``) displayed with rendering of ``PloneSite`` probably requires custom template or the component of PloneSite retrieving that with graphql.

The current ``./page/index.js`` is not pretty either. It has graphql for text/data of every document node just to be able to render contents of ``index``. So, even the current solution is not very good and you are free to fix it and tweak tests accordingly.

https://github.com/collective/gatsby-source-plone/commit/d747d3a10cfbb66f6a86f1132908e733ce8916f8#diff-c6c51c6bec27a282fdc7c5507a812feb

About ``PloneSite`` component. Forget about the previous comment and items. Instead of trying to list the items in the component, shouldn't you try to render the children? Like on Folder component?

https://github.com/collective/gatsby-source-plone/commit/d747d3a10cfbb66f6a86f1132908e733ce8916f8#diff-d557f27a35908eab3254281c006e0985

**Comment by ajayns** [comment]
Yes yes, I went for the items property cause that wouldn't require another fragment. But now I see a better approach for this, I've rebuilt the component.

**Pull request merged**
