### PR TITLE
Process and Handle remote files in plugin

### PR DESCRIPTION
**Pull request by ajayns**
References #95 

* I've assumed that a node may contain both image and file nodes at the same time.
* `tests/starter-default` is yet to be updated to illustrate file handling.

### CODE REVIEW

**Comment by ajayns** [comment]
@datakurre Tests seemed to have passed and I have linked the file node to the `file` attribute of the node for types that have files. It can be queried now and the files are downloaded to cache. 

But I'm unsure how use this in the starter?

**Comment by datakurre** [comment]
Testcases-folder have files. Try to make them visible and downloadable from the folder listing

https://collective.github.io/gatsby-source-plone/testcases

**Comment by ajayns** [comment]
Okay! I'll try that out!

**Comment by ajayns** [comment]
@datakurre Trying that out, I do have all the file data at `file` attribute, but how do make them downloadable in the page? I don't think using `Link` or `a` would work. What would be the alternative?

**Comment by ajayns** [comment]
@datakurre Trying that out, I do have all the file data at file attribute, but how do make them downloadable in the page? I don't think using Link or a would work. What would be the alternative?

**Comment by ajayns** [comment]
Documentation uses `publicURL` data field with gatsby-source-filesystem but that doesn't seem to be available for this

**Comment by datakurre** [comment]
@ajayns Have tried graphql explorer for what else there could be?

**Comment by datakurre** [comment]
@ajayns It seems that publicURL attribute is implemented in gatsby-source-filesystem. I wonder, if the plugin must be included some way to enable that.

**Comment by cekk** [comment]
i don't know if this is helps for us, because it take files from filesystem and creates nodes with them.
We already have a node and we handle that file in another way. Maybe you could see how it generates publicUrl attribute

**Comment by datakurre** [comment]
@cekk We already use gatsby-source-filesystem to create those nodes, but possibly because we don’t include it as a plugin in gatsby-config, it graphql-node-extension is not included.

**Comment by datakurre** [comment]
Copying setFieldsOnGraphQLNodeType hook from gatsby-source-filesystem/extend-file-node works, but cannot be the final solution:

https://github.com/collective/gatsby-source-plone/commit/670ff443fc7f557e4d0b9959397b181688de91c5

For reason unknown to me, setFieldsOnGraphQLNodeType did not have effect in plugin's gatsby-node.js, but worked immediately from started example's gatsby-source-node.js.

Also, I was unable to direcly import that from gatsby-source-filesystem, probably for some Gatsby V2 reason.

**Comment by datakurre** [comment]
@ajayns As a summary, I believe that the correct way to get publicURL for now would be to configure gatsby-source-filesystem plugin with some empty example directory.

**Comment by datakurre** [comment]
@ajayns Yes. That’s a git feature. It is common practice to add dummy file, often named ”.gitkeep”, to an empty folder to have it in repository.

Could the folder be named ”static”?

**Pull request merged**
