### PR TITLE
Adding mock-server

### PR DESCRIPTION
**Pull request by iFlameing**
@datakurre I successfully tested this. I am able to send the data from the server and received from the gatsby-node.js. What should be my next step? I am thinking that If I am able to know What to send from WebSocket Server I will start working on adding node :)

### CODE REVIEW

**Comment by datakurre** [comment]
About what to send. I try to invent the protocol tomorrow when I'm implementing the Plone side for it.

How about three simple possible messages (received as JSON serialized strings from websocked):

```json
{
    "created": [{
        "@id": "http://localhost:8080/...",
        "parent": {
            "@id": "http://localhost:8080/..."
        }
    }]
}
```

```json
{
    "modified": [{
        "@id": "http://localhost:8080/...",
        "parent": {
            "@id": "http://localhost:8080/..."
        }
    }]
}
```

```json
{
    "deleted": [{
        "@id": "http://localhost:8080/...",
        "parent": {
            "@id": "http://localhost:8080/..."
        }
    }]
}
```

**Comment by iFlameing** [comment]
@datakurre I tested WebSocket using setTimeout by delaying up to 2minutes and sending json serialized data and It works :)

setTimeout

**Comment by datakurre** [comment]
Great! Now this should no longer break anything, so let's merge this.

**Comment by iFlameing** [comment]
@datakurre thank you for merging this. This is my first pr after the selection as a gsoc student. It means a lot for me :)

**Comment by datakurre** [comment]
@iFlameing Congrats! Let's try to continue like that and try to work with small easy-to-merge pull requests!

**Comment by iFlameing** [comment]
@datakurre  Can you open some small issues?

**Comment by datakurre** [comment]
@iFlameing Would you be able to try first?

https://github.com/collective/gatsby-source-plone/issues/171

You've already done planning in the GSOC proposal, so good start would be to transform that planning into tickets so that they could be finished according to planned schedule.

**Comment by iFlameing** [comment]
@datakurre ok :)

**Pull request merged**
