### PR TITLE
Basic recursive approach

### PR DESCRIPTION
**Pull request by ajayns**
Addresses  #29 

Basic traversal and node creation established with BFS algorithm. Right now I haven't yet implemented handling `searchParams` it just checks it for deciding which method to use.

- [x] Basic recursive algorithm

- [x] Handling Plone Site Node

- [x] Refactor the different approaches: Modularize functions

- [ ] Handling searchParams

### CODE REVIEW

**Comment by datakurre** [comment]
@ajayns For me it looks like recursive one is missing plone site node creation.

Also, maybe it makes sense to refactor those into their own functions instead of indenting them?

**Comment by ajayns** [comment]
>For me it looks like recursive one is missing plone site node creation.

The first node that's processed by the algorithm is the baseUrl, which is the Plone Site node itself, according to my thoughts its supposed to be included. But I'll check it out once more. 

> Also, maybe it makes sense to refactor those into their own functions instead of indenting them?

Own functions meaning a function for the search traversal method, and another for recursive?

Also, about moving forward, searchParams will be a string of params? What should it ideally be?

**Comment by datakurre** [comment]
@ajayns But the baseUrl is not necessarily PloneSite.

@cekk Would you have ideas for a good search parameters format?

**Comment by ajayns** [comment]
Oh okay, I'll handle it separately and make it of type `PloneSiteNode` like we did in search traversal method. I had forgotten about this case.

**Comment by ajayns** [comment]
@datakurre This is what you meant by functions for each yes?

**Comment by ajayns** [comment]
@datakurre We still have search parameters handling pending. We'll take this discussion to the issue.

**Pull request merged**
