### PR TITLE
Image handling

### PR DESCRIPTION
**Pull request by ajayns**
References #95 

This is initial PR to handle just images. I had a doubt though, we only seem to be considering nodes of type `PloneNewsItem` handle as file nodes when required, don't we need to add type `PloneImage` also to this? @datakurre @cekk

### CODE REVIEW

**Comment by datakurre** [comment]
@ajayns Yes. Both should be handled and deprecated ”resolutions” should be replaced with ”fixed”.

**Comment by ajayns** [comment]
@datakurre I'm unsure what's causing this, but updating the plugin to v2 seems to breaking

**Comment by datakurre** [comment]
@ajayns An acceptance check to test that some image (img tag) is rendered would be nice.

**Comment by ajayns** [comment]
@datakurre I went through the robot framework docs and this was the solution I found:
```
Scenario: Image in a News Item
  Go To  http://localhost:9000/News
  Wait until page contains  News
  Click link  GSOC for Gatsby source for Plone started
  Page should contain  GSOC for Gatsby
  Page should contain Image
  Element should be visible
```
Only problem is that both `Page should contain Image` and `Element should be visible` require a unique identifier for the image such as ID etc, which we can't provide. So what would be the method to check if any image at all is rendered and visible?

**Comment by datakurre** [comment]
Fun solution would be to do image matching test, but has some difficult dependencies for your local environment.

Maybe now just

```
     Page should contain element  css=h3+img
```

**Pull request merged**
