### PR TITLE
Add tree hierarchy docs

### PR DESCRIPTION
**Pull request by ajayns**
Added some basic documentation for tree hierarchy.

### CODE REVIEW

**Comment by ajayns** [comment]
I can't give an example from our gatsby-site then, I think most of the cases where we used are pretty complex. I could maybe give a query for a generalized case, as the gist I had mentioned. Would that be a good idea? @datakurre

**Comment by datakurre** [comment]
Add something generic that would work in our example?

**Comment by datakurre** [comment]
Well, this is still good start, so I'll merge.

**Comment by datakurre** [comment]
And maybe we want to keep also this more complex example anyway.

**Comment by datakurre** [comment]
@ajayns If seems that merging this broke Travis build, which does not make sense. I clear Travis cache and retry recent builds.

**Comment by datakurre** [comment]
Retryin build fixed it.

**Pull request merged**
