### PR TITLE
Added Prettier config to editor

### PR DESCRIPTION
**Pull request by ajayns**
Addresses task 3 of #24 

Setup `.prettierrc` for editors to follow and also added documentation in readme to set it up with Visual Studio Code. As per slack discussion with @datakurre , do mention if any changes are required.

cc @cekk 
This ensures that code is auto formatted by Prettier on save.

### CODE REVIEW

**Comment by datakurre** [comment]
@ajayns Nice. I guess, we could now remove respective arguments from Makefiles.

Possibly we need to copy .prettierrc into ./tests/gatsby-something that also Makefiles in there detects it?

**Comment by ajayns** [comment]
Since we use a separate Makefile and take `./tests/gatsby-..` and consider it a project by itself, I think yes, we'll need a copy of it in there too.

**Comment by ajayns** [comment]
Okay I've updated the Makefiles and also copied `.prettierrc` to the tests folder. Hopefully I didn't mess the make build up. 

Also, I believe this Prettier plugin for editors is fully independent and wouldn't need `prettify` as a node module. (Maybe I should add a line in the readme as well about installing this plugin)

cc @datakurre

**Comment by datakurre** [comment]
Yes, I also believe it’s independent installation.

**Pull request merged**
