### PR TITLE
Update .gitignore and add .npmignore

### PR DESCRIPTION
**Pull request by ajayns**
Addresses #27 

I've taken the [npm documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) and a few other popular Gatsby plugins such as [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress) as reference.

Do let me know if this causes an issue/conflicts with Make or tests we use.

### CODE REVIEW

**Comment by cekk** [comment]
seems ok to me

**Comment by ajayns** [comment]
@datakurre @polyester opinions? Once we move forward with this, development can go on smoothly

**Comment by ajayns** [comment]
@polyester Noted, I've made the necessary changes to `.npmignore`. Also while working on this, I found that there were a few unnecessary lines in `.gitignore` that were probably there for playing around. I've removed them as well.

**Comment by cekk** [comment]
Fixes #27

**Pull request merged**
