### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ajayns**
Update all dependencies from beta to latest

Also ref: https://github.com/collective/gatsby-starter-plone/pull/20

### CODE REVIEW

**Comment by ajayns** [comment]
@datakurre It seems like a page isn't being created or so? Can you confirm it's not an issue with the Plone site used as source?

**Comment by datakurre** [comment]
Maybe @tisto, because it is the kitconcept demo site that is used as source.

**Comment by datakurre** [comment]
Oh sorry. I mixed this with gatsby-starter-plone. Sorry @tisto. This was probably because event collection in our fixter started filtering event after it happened in real life.

I'm currently fixing this in master.

**Comment by cekk** [comment]
@datakurre @ajayns what's the status of this pr?
@datakurre have you fixed something in the master or this is still valid? With updated versions of course.

**Comment by ajayns** [comment]
Seems to be an issue with the fixture or so, as I'm not able to pinpoint what went wrong to any of the dependency upgrades I made. Hopefully @datakurre has a solution

**Comment by cekk** [comment]
Good! So we can close this pr without a merge?

**Comment by ajayns** [comment]
I think the dependencies are still beta in master, I'll rebase the PR and see if that does the trick
Hold up @cekk

**Pull request merged**
