### PR TITLE
Fixes broken link in docs/tutorial

### LINKED ISSUE #159: Link for  tutorial next page gives 404 error.
while going through tutorial I found that link for next page is giving 404 error.

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #159

### CODE REVIEW

**Comment by datakurre** [comment]
Links are relative to work at https://collective.github.io/gatsby-source-plone

**Comment by datakurre** [comment]
Those docs are built through Plone to acceptance test the plugin.

**Comment by iFlameing** [comment]
ok, should I close this pr now ?

**Comment by ajayns** [comment]
Yes do close this. Please try to understand the setup first before confirming bugs and do discuss for verifying the issue. Thanks for the PR but I'm afraid it's not gonna help us

**Comment by iFlameing** [comment]
@ajayns is there any communication channel available because I didn't find it in docs. sorry if I missed it.

**Comment by ajayns** [comment]
You can use the Plone community site for discussing things and checking out the GSoC brainstorming process. The GH issue tracker is also used by us for the same. But please do be patient on us getting back to you on things cause we could be caught up as well.

**Comment by iFlameing** [comment]
ok, Now I am closing this pull request.

**Pull request closed without merging**
