### PR TITLE
Clean up code, add helpers, basic traversal

### PR DESCRIPTION
**Pull request by ajayns**
Cleaned up the code, refactored the the functions and added helpers.
It's now a basic working prototype.

@datakurre I'm not sure how often I should update the changelog? I'll do that every week just adding all the changes made?

### CODE REVIEW

**Comment by datakurre** [comment]
Changelog should include only the meaningful things:

incompatible changes to the previous version

new features

bugs fixed

**Comment by ajayns** [comment]
Yes I have checked out the sample changelog you mentioned. But how often should I update it? With every PR? @datakurre

**Comment by datakurre** [comment]
@ajayns For Plone we require changelog updates for each pull request, but that mostly because different people do the pull requests and releases. In this GSOC its well ok to only update changelog for releases.

**Comment by datakurre** [comment]
I assume this does single url publishing. I merge and try this out. I'm planning to add automatic deploy to gh-pages from the test data.

**Comment by ajayns** [comment]
@datakurre auto deploying would only work if our gatsby-starter-default package pulled data from an online plone site and not from a local site yes?

**Comment by datakurre** [comment]
Auto deploy would work from the acceptance test we already have. Every Travis-CI builds already a static site. I just configure deploy for it.

**Comment by ajayns** [comment]
Oh alright that makes sense! @datakurre

**Pull request merged**
