### PR TITLE
Shift to Docker for plone.restapi

### PR DESCRIPTION
**Pull request by ajayns**
References #18 

* Updated Makefile
* Added `docker-compose.yml`
* Removed `/api`
* Updated README.md

### CODE REVIEW

**Comment by cekk** [comment]
@ajayns i think that you removed too many lines, or you need to update the test script: it fails because try to execute build-test

**Comment by ajayns** [comment]
Should I add `docker-compose up` in the Makefile? Is that's what's causing this? 

cc @datakurre

**Comment by datakurre** [comment]
Yes. But I admit that I forgot Travis part...

At least we need to add docker service into .travis.yml, but possibly we also need to create a Python virtualenv for docker-compose.

I’ll try to find time to help with that later today.

https://docs.travis-ci.com/user/docker/

**Comment by ajayns** [comment]
I'll do a bit of research on that and try to fix, also, everything else looks good? @datakurre

**Comment by datakurre** [comment]
@ajayns I'm working on this and will provide a working example with info later today.

**Comment by datakurre** [comment]
@ajayns I'm sorry for pushing directly to your branch. I was not aware that you had given use write permissions.

I'll explain the changes a bit later. (Been doing this a bit by bit during the day.)

**Comment by datakurre** [comment]
@ajayns When you are online, you could try how running just ``make test`` works on your machine.

**Comment by ajayns** [comment]
@datakurre That's how I had moved forward while contributing to Gatsby and so I had left the write permissions on. And yes, pulling from branch and checking out the changes

**Comment by ajayns** [comment]
I see that you're still pushing commits. Should I wait before I pull and run tests?

**Comment by datakurre** [comment]
@ajayns Yes. Let's wait that Travis gets green.

**Comment by ajayns** [comment]
Okay good to go, let's check this out.

**Comment by datakurre** [comment]
Green finally. Then the long story.

At first, during this summer, spend some time learning GNU make. Any short tutorial like this should help to get started: https://www.sitepoint.com/using-gnu-make-front-end-development-build-tool/ It seems that every language and every community keeps reinventing basic build tools, but at the end return to use make. It's ubiquitous, mature and good language agnostic fit for modern polyglot development.

I split the previous Makefile into one at the project root ``./Makefile`` and the second at ``./tests/gatsby-starter-default/Makefile`` to keep them simple.

While ``clean`` is standard make target (``make clean``) for removing the build artifacts I use to separate build artifacts from dependencies. Here  ``make clean`` only remove the gatsby build and ``make purge`` resets the environment by removing also ``node_modules`` and Docker compose containers.

I added ``make prettier``.

This still uses ``yarn link`` to symlink the plugin to the test project.

``.PHONY: target`` on Makefile means that the target does not relate to a path. Make defaults to consider every target as a file / path / dependency created by the target.

``shell.nix`` is only for me (or someone else using NixOS). Don't let it bother you.

Travis is no longer special ``.travis.yml`` is simple and mostly includes ``make test`` that should also work on any OSX or Linux. Makefile does include some magic to select the correct geckodriver version for OSX and Linux (required for running the tests).

Python 3 is required for running the tests. (On OSX it can be installed e.g. with homebrew).

``make public`` is the target that starts Plone docker container with ``docker-compose up -d`` (-d for detached / on the backround), runs gatsby and then stops the container.

``make test`` is the most complex make target, because it needs to start gatsby serve, run the test, save the exit code from tests, stop gatsby serve and then return the exit status from tests (to signal failing tests properly).

**Comment by datakurre** [comment]
@ajayns We can merge this once you are able to run ``make test`` on your own machine successfully.

I'm sorry for hijacking this. Once I looked this I realized that the testing part made this non-trivial and though this should just be done to let you focus on gatsbyjs stuff.

In the future, we may need to add more test fixture into test Plone site (now its empty). That can done similarly to ``make public`` in test directory Makefile, but instead of ``gatsby build`` we would call a script that populates the site using Plone REST API (as long as docker container is not removed, it should keep its data).

**Comment by datakurre** [comment]
Oh, I also added yarn lock files into repo (they were accidentally in .gitignore), because IMO the whole idea in them is to ensure reproducible environments (the exact same versions).

**Comment by datakurre** [comment]
After playing around a bit, I though that it might be best to leave Plone docker container running on the background until explicitly stopped (either make stop or make purge). That make sequential make build a bit faster.

**Comment by ajayns** [comment]
@datakurre I've gone through what you've done and it's making sense, but I'll still need to read up a lot more to properly understand. Also, the make seems to be working fine on my machine, I think this can be merged.

**Pull request merged**
